-- ═══════════════════════════════════════════════════════
-- ENCUESTASS — Schema para PostgreSQL (NeonDB)
-- ═══════════════════════════════════════════════════════

-- Extensión para UUID
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ROLES
CREATE TABLE IF NOT EXISTS roles (
    IDROL SERIAL PRIMARY KEY,
    ROL VARCHAR(100) NOT NULL
);

-- USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
    IDUSUARIO SERIAL PRIMARY KEY,
    USUARIO VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL INT NOT NULL REFERENCES roles(IDROL),
    ESTADO BOOLEAN DEFAULT TRUE
);

-- ORGANISMOS
CREATE TABLE IF NOT EXISTS organismos (
    ID_ORGANISMO SERIAL PRIMARY KEY,
    ORGANISMO VARCHAR(255) NOT NULL
);

-- DIRECTORIO I.E.
CREATE TABLE IF NOT EXISTS directorio_ie (
    ITEM SERIAL PRIMARY KEY,
    INSTITUCION_EDUCATIVA VARCHAR(255) NOT NULL
);

-- MENU
CREATE TABLE IF NOT EXISTS menu (
    IDBOTON VARCHAR(50) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    BOTON VARCHAR(255) NOT NULL
);

-- JORNADAS
CREATE TABLE IF NOT EXISTS jornadas (
    ID_JORNADA SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA DATE NOT NULL,
    LUGAR VARCHAR(255),
    DIRECCION VARCHAR(255),
    RESPONSABLE VARCHAR(255),
    META_ENCUESTADOS INT DEFAULT 0,
    TIPO_PUBLICO VARCHAR(20) DEFAULT 'SERVIDOR',
    ORGANISMO_ID INT REFERENCES organismos(ID_ORGANISMO),
    NOMBRE_ORGANISMO VARCHAR(255),
    INSTITUCION_EDUCATIVA_ID INT REFERENCES directorio_ie(ITEM),
    NOM_INS_EDUCATIVA VARCHAR(255),
    ESTADO VARCHAR(20) DEFAULT 'ACTIVA',
    CREADO_POR VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PIN VARCHAR(20),
    ENC_CIUDADANOS BOOLEAN DEFAULT FALSE,
    ENC_QUIZ BOOLEAN DEFAULT FALSE,
    ENC_PRESABER BOOLEAN DEFAULT FALSE,
    ENC_CIUDADANOS_ACTIVA BOOLEAN DEFAULT FALSE,
    ENC_QUIZ_ACTIVA BOOLEAN DEFAULT FALSE,
    ENC_PRESABER_ACTIVA BOOLEAN DEFAULT FALSE
);

-- ENCUESTAS CIUDADANOS
CREATE TABLE IF NOT EXISTS encuestas_ciudadanos (
    ID_ENCUESTA VARCHAR(50) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    USUARIO VARCHAR(255),
    FECHA DATE NOT NULL,
    ESTUDIOS VARCHAR(255),
    OCUPACION VARCHAR(255),
    "Pregunta_1" VARCHAR(50),
    "Pregunta_2" VARCHAR(50),
    "Pregunta_3" VARCHAR(50),
    "Pregunta_4" VARCHAR(50),
    "Pregunta_5" VARCHAR(50),
    "Pregunta_6" VARCHAR(50),
    "Pregunta_7" VARCHAR(50),
    ID_JORNADA INT REFERENCES jornadas(ID_JORNADA)
);

-- PREGUNTAS (Quiz)
CREATE TABLE IF NOT EXISTS preguntas (
    ID_RESPUESTA SERIAL PRIMARY KEY,
    USUARIO VARCHAR(255),
    FECHA DATE NOT NULL,
    SERVIDOR_PUBLICO_PLANTA VARCHAR(10),
    CARGO VARCHAR(255),
    PROFESION VARCHAR(255),
    ORGANISMO_P INT REFERENCES organismos(ID_ORGANISMO),
    NOMBRE_ORGANISMO VARCHAR(255),
    INSTITUCION_EDUCATIVA INT REFERENCES directorio_ie(ITEM),
    NOM_INS_EDUCATIVA VARCHAR(255),
    CAPACITACION_LEY_DISCIPLINARIA VARCHAR(10),
    P1 VARCHAR(255),
    P2 VARCHAR(255),
    P3 VARCHAR(255),
    P4 VARCHAR(255),
    P5 VARCHAR(255),
    P6 VARCHAR(255),
    P7 VARCHAR(255),
    P8 VARCHAR(255),
    ID_JORNADA INT REFERENCES jornadas(ID_JORNADA)
);

-- PRESABER
CREATE TABLE IF NOT EXISTS presaber (
    ID_RESPUESTA SERIAL PRIMARY KEY,
    USUARIO VARCHAR(255),
    FECHA DATE NOT NULL,
    SERVIDOR_PUBLICO_PLANTA VARCHAR(10),
    CARGO VARCHAR(255),
    PROFESION VARCHAR(255),
    ORGANISMO VARCHAR(255),
    INSTITUCION_EDUCATIVA VARCHAR(255),
    CAPACITACION_LEY VARCHAR(10),
    CUANTAS INT,
    Q1 VARCHAR(10), Q2 VARCHAR(10), Q3 VARCHAR(10), Q4 VARCHAR(10),
    Q5 VARCHAR(10), Q6 VARCHAR(10), Q7 VARCHAR(10), Q8 VARCHAR(10),
    ANIO INT,
    MES VARCHAR(20),
    ID_JORNADA INT REFERENCES jornadas(ID_JORNADA)
);

-- DISPOSITIVOS JORNADA (cookie única por celular)
CREATE TABLE IF NOT EXISTS dispositivos_jornada (
    ID SERIAL PRIMARY KEY,
    DISPOSITIVO_TOKEN VARCHAR(64) NOT NULL,
    ID_JORNADA INT NOT NULL REFERENCES jornadas(ID_JORNADA),
    RESPONDIDAS VARCHAR(255) DEFAULT '',
    COMPLETADO BOOLEAN DEFAULT FALSE,
    PRIMERA_VEZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ACTIVIDAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_REGISTRO VARCHAR(45),
    UNIQUE (DISPOSITIVO_TOKEN, ID_JORNADA)
);

-- Datos base
INSERT INTO roles (ROL) VALUES ('Administrador'), ('Usuario'), ('Invitado')
    ON CONFLICT DO NOTHING;
INSERT INTO usuarios (USUARIO, PASSWORD, ROL, ESTADO)
    VALUES ('admin', 'admin123', 1, TRUE)
    ON CONFLICT DO NOTHING;
